-- MySQL Script generated by MySQL Workbench
-- Mon Jul  8 21:10:38 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema fitness
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fitness
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fitness` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `fitness` ;

-- -----------------------------------------------------
-- Table `fitness`.`routine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fitness`.`routine` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `fitness`.`routine` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `level` VARCHAR(45) NULL,
  `length` VARCHAR(45) NULL,
  `desc` LONGTEXT NULL,
  `style` VARCHAR(255) NULL,
  `goal` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fitness`.`rExercise`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fitness`.`rExercise` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `fitness`.`rExercise` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `set` VARCHAR(45) NULL,
  `rpe` VARCHAR(45) NULL,
  `weight` VARCHAR(45) NULL,
  `desc` LONGTEXT NULL,
  `routine_id` INT NULL,
  `order` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id`
    FOREIGN KEY (`routine_id`)
    REFERENCES `fitness`.`routine` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fitness`.`program`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fitness`.`program` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `fitness`.`program` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `level` VARCHAR(45) NULL,
  `length` LONGTEXT NULL,
  `desc` VARCHAR(45) NULL,
  `style` VARCHAR(255) NULL,
  `goal` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fitness`.`cycle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fitness`.`cycle` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `fitness`.`cycle` (
  `id` INT NOT NULL,
  `order` INT NULL,
  `title` VARCHAR(45) NULL,
  `program_id` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id`
    FOREIGN KEY (`program_id`)
    REFERENCES `fitness`.`program` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fitness`.`pExercise`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fitness`.`pExercise` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `fitness`.`pExercise` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `set` VARCHAR(45) NULL,
  `rpe` VARCHAR(45) NULL,
  `weight` VARCHAR(45) NULL,
  `desc` LONGTEXT NULL,
  `is_rest` TINYINT NULL,
  `order` INT NULL,
  `cycle_id` INT NULL,
  `day` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id`
    FOREIGN KEY (`cycle_id`)
    REFERENCES `fitness`.`cycle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
